---
title: "price"
author: "qiufei"
date: "August 21, 2015"
output: 
  html_document: 
    fig_height: 7
    fig_width: 9
    keep_md: yes
---

I want to see the difference between ppi and cpi of china.


# load needed packages

```{r,message=FALSE}
library(knitr)
library(ggplot2)
library(reshape2)
library(Quandl)
```

the ppi and cpi data are preceding month=100.

# get ppi data

```{r}
ppi=Quandl("NBSC/A01080701_M")

```
# plot ppi

```{r}
ggplot(data=ppi,aes(x=as.Date(Date),y=Value,color=Value))+geom_line()+geom_point()
```

# get cpi data
```{r}
cpi=Quandl("NBSC/A01030101_M")

```

# plot cpi
```{r}
ggplot(data=cpi,aes(x=as.Date(Date),y=Value,color=Value))+geom_line()+geom_point()
```

# merge cpi and ppi
```{r}
price_wide=merge(cpi,ppi,by='Date')
## merge through the by option will only merge dataframe with the same variable name of the varible after by=.
## since ppi time is shorter than cpi but has same time interval, this is to get cpi and ppi in same time period.

colnames(price_wide)=c('date','cpi','ppi')

price=melt(price_wide,id.vars = 'date',variable.name = 'index',value.name = 'pi')

```

#plot cpi and ppi in one figure

```{r}
ggplot(data=price,aes(x=as.Date(date),y=pi,color=index))+geom_line()+geom_point()
```

