---
title: "金融"
author: "qiufei"
date: "2016-03-04"
output: 
  html_document: 
    fig_height: 7
    fig_width: 14
    keep_md: yes
    number_sections: yes
    theme: readable
    toc: yes
---

```{r setup,Message=FALSE,echo=FALSE,include=FALSE,warning=FALSE}

# load needed packages
library(knitr)
opts_chunk$set(Message=FALSE,echo=FALSE,fig.align = 'center')
library(ggplot2)
library(reshape2)
library(Quandl)
library(quantmod)
options("getSymbols.warning4.0"=FALSE)
library(scales)
library(plyr)
library(dplyr)
options(warn=-1)                        #suprress warning globally
## the default is
## options(warn=0)

```


# M2 for China

Monthly, Not Seasonally Adjusted

## get data from fred

```{r m2 of china,message=FALSE}

m2cn = getSymbols('MYAGM2CNM189N',src='FRED',auto.assign=FALSE)

chartSeries(m2cn,name="China M2 in CNY")

```


## M2 growth rate--month and year

```{r growth rate}

cnm2=data.frame(month=time(m2cn),M2=coredata(m2cn))
colnames(cnm2)=c('month','M2')

cnm2.month = mutate(cnm2,gr = M2/lag(M2)-1)
ggplot(data=cnm2.month,aes(x=as.Date(month),y=gr))+geom_line(color = 'red')+ggtitle('中国M2月度增长率')

summary(cnm2.month$gr)

tail(cnm2.month$gr,1)

## get the annual M2 grwoth rate
## You can use the .index* family of functions to get certain months or certain days of the month.
## note zero-based indexing!
cnm2.annual = m2cn[.indexmon(m2cn)==11]

cnm2.year=data.frame(month=time(cnm2.annual),M2=coredata(cnm2.annual))
colnames(cnm2.year)=c('month','M2')

cnm2.year = mutate(cnm2.year,gr = M2/lag(M2)-1)

ggplot(data=cnm2.year,aes(x=month,y=gr))+
    geom_line(color = 'red')+
    xlab('year')+
    ggtitle('中国M2年度增长率')

summary(cnm2.year$gr)

tail(cnm2.year$gr,1)


```

# m0,m1,m2

```{r m0m1m2}

money=Quandl("PBCHINA/REP_07", authcode="9iGeZZoG6Vc46rfs1AgJ")

money.gr = transmute(money,
                     month = Date,
                     M2g = lag(M2)/M2-1,
                     M1g = lag(M1)/M1-1,
                     M0g = lag(M0)/M0-1
                     )

kable(summary(money.gr[,-1]))

money.plot=melt(data=money.gr,id.vars = 'month',variable.name = 'm012',value.name = 'yiyuan')

ggplot(data=money.plot,aes(x=as.Date(month),y=yiyuan,color=m012))+geom_line()+geom_point()


```


